REM C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\link.exe

link^
 /ERRORREPORT:QUEUE^
 /OUT:"C:\STU\devel\ReMoM\build\tests\unit\Release\testLearning.exe"^
 /INCREMENTAL:NO^
 /NOLOGO^
 /LIBPATH:"C:\Python311\Lib\site-packages\vcpkgpip\vcpkg\installed\x64-windows\lib"^
 /LIBPATH:"C:\Python311\Lib\site-packages\vcpkgpip\vcpkg\installed\x64-windows\lib\manual-link"^
 ..\..\lib\Release\gtest_main.lib^
 ..\..\src\Release\momlib.lib^
 ..\..\src\MOX\Release\MOX.lib^
 ..\..\src\STU\Release\STU.lib^
 ..\..\lib\Release\gtest.lib^
 "C:\devellib\SDL2_mixer-2.8.1\lib\x64\SDL2_mixer.lib"^
 "C:\devellib\SDL2-2.32.2\lib\x64\SDL2main.lib"^
 "C:\devellib\SDL2-2.32.2\lib\x64\SDL2.lib"^
 kernel32.lib^
 user32.lib^
 gdi32.lib^
 winspool.lib^
 shell32.lib^
 ole32.lib^
 oleaut32.lib^
 uuid.lib^
 comdlg32.lib^
 advapi32.lib^
 "C:\Python311\Lib\site-packages\vcpkgpip\vcpkg\installed\x64-windows\lib\*.lib"^
 /MANIFEST^
 /MANIFESTUAC:"level='asInvoker' uiAccess='false'"^
 /manifest:embed^
 /PDB:"C:/STU/devel/ReMoM/build/tests/unit/Release/testLearning.pdb"^
 /SUBSYSTEM:CONSOLE^
 /TLBID:1^
 /DYNAMICBASE^
 /NXCOMPAT^
 /IMPLIB:"C:/STU/devel/ReMoM/build/tests/unit/Release/testLearning.lib"^
 /MACHINE:X64^
 /machine:x64^
 testLearning.dir\Release\testLearning.obj
