/*
    WIZARDS.EXE
        seg005
        seg006
    MoO2:
        Module: exit
*/

#ifndef EXIT_H
#define EXIT_H

#include "MoX_TYPE.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  seg005
*/

// WZD s05p01
// void Exit_With_Size(void);

// WZD s05p02
// TODO  void Exit_With_Message(char * string);

// WZD s05p03
// void Exit_With_Value(int16_t value);

// WZD s05p04
// GAME_EXE_Swap()

// WZD s05p05
// Update_MemFreeWorst_KB()

// WZD s05p06
// UU_VGA_B800Dump()

// WZD s05p07
// UU_VGA_TextModeString()



/*
    WIZARDS.EXE  seg006
*/

// WZD s06p01
// VGA_SetTextMode()

// WZD s06p02
// TODO  void Quit_With_Message(char * string);

// WZD s06p03
// UU_DOS_PrintString2()

// WZD s06p04
// RAM_GetFreeBlockSize()

// WZD s06p05
// s06p05_Empty_pFxn()

// WZD s06p06
// s06p06_Empty_pFxn()



#ifdef __cplusplus
}
#endif

#endif  /* EXIT_H */
