/*
    gen_tables.c - Trigonometric Lookup Table Generator

    Generates the pre-computed fixed-point trigonometric lookup tables
    used by Master of Magic (WIZARDS.EXE seg034).

    In the DOS era, developers used tools like this to pre-compute
    tables on their development workstations, avoiding slow floating-point
    math at runtime on 386/486 processors.

    Fixed-point formats:
        Tangent:   8.8 fixed-point (scale factor 256)
        Sin/Cos:   0.16 fixed-point (scale factor 65536)

    Build:
        gcc -Wall -O2 -o gen_tables gen_tables.c -lm

    Usage:
        gen_tables           Verify generated tables against WIZARDS.EXE data
        gen_tables --emit    Output tables as C source code
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define PI 3.14159265358979323846


/*
    Expected values extracted from disassembly of WIZARDS.EXE seg034
    (reproduced in MoX/src/angle.c)

    Tangents_0_44:  seg034:0006  45 bytes  (uint8  array)
    Tangents_45_89: seg034:00E7  90 bytes  (uint16 array)
    Sin_Multipliers: seg034:0033 180 bytes (uint16 array)
    Cos_Multipliers: seg034:0141 180 bytes (uint16 array)
*/

static const unsigned char expected_tan_0_44[45] = {
    /* floor(tan(deg) * 256) for deg = 0..44 */
      0,  4,  8, 13, 17, 22, 26, 31, 35, 40,
     45, 49, 54, 59, 63, 68, 73, 78, 83, 88,
     93, 98,103,108,113,119,124,130,136,141,
    147,153,159,166,172,179,185,192,200,207,
    214,222,230,238,247
};

static const unsigned short expected_tan_45_89[45] = {
    /* floor(tan(deg) * 256) for deg = 45..89 */
      256,  265,  274,  284,  294,  305,  316,  327,  339,  352,
      365,  379,  394,  409,  426,  443,  461,  481,  502,  524,
      548,  574,  603,  633,  666,  703,  743,  787,  837,  892,
      955, 1026, 1108, 1204, 1317, 1451, 1616, 1821, 2085, 2435,
     2926, 3661, 4885, 7331,14669
};

static const unsigned short expected_sin[90] = {
    /* floor(sin(deg) * 65536) for deg = 0..89 */
    0x0000,0x0477,0x08EF,0x0D65,0x11DB,0x164F,0x1AC2,0x1F32,
    0x23A0,0x280C,0x2C74,0x30D8,0x3539,0x3996,0x3DEE,0x4242,
    0x4690,0x4AD8,0x4F1B,0x5358,0x578E,0x5BBE,0x5FE6,0x6407,
    0x681F,0x6C30,0x7039,0x7438,0x782F,0x7C1C,0x8000,0x83D9,
    0x87A8,0x8B6D,0x8F27,0x92D5,0x9679,0x9A10,0x9D9C,0xA11B,
    0xA48D,0xA7F3,0xAB4C,0xAE97,0xB1D5,0xB505,0xB826,0xBB3A,
    0xBE3E,0xC134,0xC41B,0xC6F3,0xC9BB,0xCC73,0xCF1B,0xD1B4,
    0xD43B,0xD6B3,0xD919,0xDB6F,0xDDB3,0xDFE7,0xE208,0xE419,
    0xE617,0xE803,0xE9DE,0xEBA6,0xED5B,0xEEFF,0xF08F,0xF20D,
    0xF378,0xF4D0,0xF615,0xF746,0xF865,0xF970,0xFA67,0xFB4B,
    0xFC1C,0xFCD9,0xFD82,0xFE17,0xFE99,0xFF06,0xFF60,0xFFA6,
    0xFFD8,0xFFF6
};

static const unsigned short expected_cos[90] = {
    /* floor(cos(deg) * 65536) for deg = 1..90 */
    0xFFF6,0xFFD8,0xFFA6,0xFF60,0xFF06,0xFE98,0xFE17,0xFD82,
    0xFCD9,0xFC1C,0xFB4B,0xFA67,0xF970,0xF865,0xF746,0xF615,
    0xF4D0,0xF378,0xF20D,0xF08F,0xEEFF,0xED5B,0xEBA6,0xE9DE,
    0xE803,0xE617,0xE418,0xE208,0xDFE7,0xDDB3,0xDB6F,0xD919,
    0xD6B3,0xD43B,0xD1B3,0xCF1B,0xCC73,0xC9BB,0xC6F2,0xC41B,
    0xC134,0xBE3E,0xBB39,0xB826,0xB504,0xB1D5,0xAE97,0xAB4C,
    0xA7F3,0xA48D,0xA11B,0x9D9B,0x9A10,0x9678,0x92D5,0x8F27,
    0x8B6D,0x87A8,0x83D9,0x7FFF,0x7C1C,0x782F,0x7438,0x7038,
    0x6C30,0x681F,0x6406,0x5FE6,0x5BBD,0x578E,0x5358,0x4F1B,
    0x4AD8,0x468F,0x4241,0x3DEE,0x3996,0x3539,0x30D8,0x2C73,
    0x280B,0x23A0,0x1F32,0x1AC2,0x164F,0x11DB,0x0D65,0x08EE,
    0x0477,0x0000
};


static void emit_tables(
    const unsigned char  *tan_0_44,
    const unsigned short *tan_45_89,
    const unsigned short *sin_tbl,
    const unsigned short *cos_tbl)
{
    int i;

    printf("/* Generated by tools/angles/gen_tables.c */\n\n");

    /* Tangents_0_44 */
    printf("/* floor(tan(deg) * 256) for deg = 0..44 */\n");
    printf("static const uint8_t Tangents_0_44[45] = {\n");
    for (i = 0; i < 45; i++)
    {
        if (i % 9 == 0) printf("    ");
        printf("0x%02X", tan_0_44[i]);
        if (i < 44) printf(",");
        if ((i + 1) % 9 == 0 || i == 44) printf("\n");
    }
    printf("};\n\n");

    /* Tangents_45_89 */
    printf("/* floor(tan(deg) * 256) for deg = 45..89 */\n");
    printf("static const uint16_t Tangents_45_89[45] = {\n");
    for (i = 0; i < 45; i++)
    {
        if (i % 8 == 0) printf("    ");
        printf("0x%04X", tan_45_89[i]);
        if (i < 44) printf(",");
        if ((i + 1) % 8 == 0 || i == 44) printf("\n");
    }
    printf("};\n\n");

    /* angle_to_sin */
    printf("/* floor(sin(deg) * 65536) for deg = 0..89 */\n");
    printf("static const uint16_t angle_to_sin[90] = {\n");
    for (i = 0; i < 90; i++)
    {
        if (i % 8 == 0) printf("    ");
        printf("0x%04X", sin_tbl[i]);
        if (i < 89) printf(",");
        if ((i + 1) % 8 == 0 || i == 89) printf("\n");
    }
    printf("};\n\n");

    /* angle_to_cos */
    printf("/* floor(cos(deg) * 65536) for deg = 1..90 */\n");
    printf("static const uint16_t angle_to_cos[90] = {\n");
    for (i = 0; i < 90; i++)
    {
        if (i % 8 == 0) printf("    ");
        printf("0x%04X", cos_tbl[i]);
        if (i < 89) printf(",");
        if ((i + 1) % 8 == 0 || i == 89) printf("\n");
    }
    printf("};\n");
}


static int verify_table_u8(
    const char *name,
    const unsigned char *generated,
    const unsigned char *expected,
    int count,
    int deg_offset)
{
    int i, mm = 0;

    printf("%s  [%d entries, uint8]\n", name, count);
    for (i = 0; i < count; i++)
    {
        if (generated[i] != expected[i])
        {
            printf("  [%2d] %2d deg: expected %3u (0x%02X), got %3u (0x%02X), diff %+d\n",
                i, i + deg_offset,
                expected[i], expected[i],
                generated[i], generated[i],
                (int)generated[i] - (int)expected[i]);
            mm++;
        }
    }
    printf("  Result: %s (%d/%d match)\n\n",
        mm == 0 ? "PASS" : "FAIL", count - mm, count);
    return mm;
}


static int verify_table_u16(
    const char *name,
    const unsigned short *generated,
    const unsigned short *expected,
    int count,
    int deg_offset)
{
    int i, mm = 0;

    printf("%s  [%d entries, uint16]\n", name, count);
    for (i = 0; i < count; i++)
    {
        if (generated[i] != expected[i])
        {
            printf("  [%2d] %2d deg: expected %5u (0x%04X), got %5u (0x%04X), diff %+d\n",
                i, i + deg_offset,
                expected[i], expected[i],
                generated[i], generated[i],
                (int)generated[i] - (int)expected[i]);
            mm++;
        }
    }
    printf("  Result: %s (%d/%d match)\n\n",
        mm == 0 ? "PASS" : "FAIL", count - mm, count);
    return mm;
}


int main(int argc, char *argv[])
{
    int emit_mode = (argc > 1 && strcmp(argv[1], "--emit") == 0);
    unsigned char  gen_tan_0_44[45];
    unsigned short gen_tan_45_89[45];
    unsigned short gen_sin[90];
    unsigned short gen_cos[90];
    int i;
    double rad, val;

    /*
        Generate Tangents_0_44
        floor(tan(i deg) * 256) for i = 0..44
        Scale factor 256 = 8.8 fixed-point
        tan(44) * 256 = 247, fits in uint8
    */
    for (i = 0; i <= 44; i++)
    {
        rad = i * (PI / 180.0);
        val = tan(rad) * 256.0;
        gen_tan_0_44[i] = (unsigned char)val;
    }

    /*
        Generate Tangents_45_89
        floor(tan(i deg) * 256) for i = 45..89
        tan(45) * 256 = 256, needs uint16
        tan(89) * 256 = ~14666, fits in uint16
    */
    for (i = 45; i <= 89; i++)
    {
        rad = i * (PI / 180.0);
        val = tan(rad) * 256.0;
        gen_tan_45_89[i - 45] = (unsigned short)val;
    }

    /*
        Generate Sin table
        floor(sin(i deg) * 65536) for i = 0..89
        Scale factor 65536 = 0.16 fixed-point
        sin(89) * 65536 = 65526, fits in uint16
    */
    for (i = 0; i <= 89; i++)
    {
        rad = i * (PI / 180.0);
        val = sin(rad) * 65536.0;
        gen_sin[i] = (unsigned short)val;
    }

    /*
        Generate Cos table
        floor(cos(i deg) * 65536) for i = 1..90
        cos(1) * 65536 = 65526, cos(90) * 65536 = 0
    */
    for (i = 1; i <= 90; i++)
    {
        rad = i * (PI / 180.0);
        val = cos(rad) * 65536.0;
        gen_cos[i - 1] = (unsigned short)val;
    }


    if (emit_mode)
    {
        emit_tables(gen_tan_0_44, gen_tan_45_89, gen_sin, gen_cos);
        return 0;
    }


    /* --- Verify mode --- */
    int total_mismatches = 0;

    printf("Angle Lookup Table Verification\n");
    printf("================================\n");
    printf("Comparing generated tables against WIZARDS.EXE seg034 data\n\n");

    total_mismatches += verify_table_u8(
        "Tangents_0_44 ", gen_tan_0_44, expected_tan_0_44, 45, 0);

    total_mismatches += verify_table_u16(
        "Tangents_45_89", gen_tan_45_89, expected_tan_45_89, 45, 45);

    total_mismatches += verify_table_u16(
        "angle_to_sin  ", gen_sin, expected_sin, 90, 0);

    total_mismatches += verify_table_u16(
        "angle_to_cos  ", gen_cos, expected_cos, 90, 1);

    printf("================================\n");
    printf("Total: %d / 270 entries match\n", 270 - total_mismatches);

    if (total_mismatches == 0)
    {
        printf("VERIFIED: All tables match WIZARDS.EXE seg034 data exactly.\n");
    }
    else
    {
        printf("%d entries differ.\n", total_mismatches);
        printf("Differences of +/-1 are expected due to Borland C++ 3.0\n");
        printf("x87 FPU precision vs modern IEEE 754 double precision.\n");
    }

    return total_mismatches > 0 ? 1 : 0;
}
