# CMake generated Testfile for 
# Source directory: C:/STU/devel/ReMoM/tests
# Build directory: C:/STU/devel/ReMoM/build-dbg/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/STU/devel/ReMoM/build-dbg/tests/hello_test[1]_include.cmake")
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_WorldGen_Run "C:/STU/devel/ReMoM/build-dbg/bin/Debug/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_WorldGen_Run PROPERTIES  FIXTURES_SETUP "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Debug" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;32;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_WorldGen_Run "C:/STU/devel/ReMoM/build-dbg/bin/Release/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_WorldGen_Run PROPERTIES  FIXTURES_SETUP "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Release" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;32;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_WorldGen_Run "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_WorldGen_Run PROPERTIES  FIXTURES_SETUP "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;32;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_WorldGen_Run "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_WorldGen_Run PROPERTIES  FIXTURES_SETUP "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;32;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_WorldGen_Run NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_WorldGen_Validate "C:/Program Files/CMake/bin/cmake.exe" "-DSAVE_FILE=C:/STU/devel/ReMoM/build-dbg/bin/Debug/SAVE9.GAM" "-DEXPECTED_SIZE=123300" "-P" "C:/STU/devel/ReMoM/tests/validate_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Validate PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;45;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_WorldGen_Validate "C:/Program Files/CMake/bin/cmake.exe" "-DSAVE_FILE=C:/STU/devel/ReMoM/build-dbg/bin/Release/SAVE9.GAM" "-DEXPECTED_SIZE=123300" "-P" "C:/STU/devel/ReMoM/tests/validate_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Validate PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;45;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_WorldGen_Validate "C:/Program Files/CMake/bin/cmake.exe" "-DSAVE_FILE=C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/SAVE9.GAM" "-DEXPECTED_SIZE=123300" "-P" "C:/STU/devel/ReMoM/tests/validate_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Validate PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;45;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_WorldGen_Validate "C:/Program Files/CMake/bin/cmake.exe" "-DSAVE_FILE=C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/SAVE9.GAM" "-DEXPECTED_SIZE=123300" "-P" "C:/STU/devel/ReMoM/tests/validate_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Validate PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;45;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_WorldGen_Validate NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_WorldGen_Golden "C:/Program Files/CMake/bin/cmake.exe" "-DACTUAL=C:/STU/devel/ReMoM/build-dbg/bin/Debug/SAVE9.GAM" "-DEXPECTED=C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.GAM" "-P" "C:/STU/devel/ReMoM/tests/compare_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Golden PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;63;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_WorldGen_Golden "C:/Program Files/CMake/bin/cmake.exe" "-DACTUAL=C:/STU/devel/ReMoM/build-dbg/bin/Release/SAVE9.GAM" "-DEXPECTED=C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.GAM" "-P" "C:/STU/devel/ReMoM/tests/compare_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Golden PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;63;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_WorldGen_Golden "C:/Program Files/CMake/bin/cmake.exe" "-DACTUAL=C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/SAVE9.GAM" "-DEXPECTED=C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.GAM" "-P" "C:/STU/devel/ReMoM/tests/compare_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Golden PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;63;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_WorldGen_Golden "C:/Program Files/CMake/bin/cmake.exe" "-DACTUAL=C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/SAVE9.GAM" "-DEXPECTED=C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.GAM" "-P" "C:/STU/devel/ReMoM/tests/compare_save.cmake")
  set_tests_properties(HeMoM_WorldGen_Golden PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;63;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_WorldGen_Golden NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_WorldGen_Fields "C:/STU/devel/ReMoM/build-dbg/bin/Debug/compare_save_text.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Debug/SAVE9.txt" "C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.txt")
  set_tests_properties(HeMoM_WorldGen_Fields PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;85;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_WorldGen_Fields "C:/STU/devel/ReMoM/build-dbg/bin/Release/compare_save_text.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Release/SAVE9.txt" "C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.txt")
  set_tests_properties(HeMoM_WorldGen_Fields PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;85;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_WorldGen_Fields "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/compare_save_text.exe" "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/SAVE9.txt" "C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.txt")
  set_tests_properties(HeMoM_WorldGen_Fields PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;85;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_WorldGen_Fields "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/compare_save_text.exe" "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/SAVE9.txt" "C:/STU/devel/ReMoM/tests/golden_worldgen_seed12345.txt")
  set_tests_properties(HeMoM_WorldGen_Fields PROPERTIES  FIXTURES_REQUIRED "HeMoM_WorldGen" LABELS "hemom;integration;worldgen;golden" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;85;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_WorldGen_Fields NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_Continue_Setup "C:/STU/devel/ReMoM/build-dbg/bin/Debug/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_Continue_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_Continue" LABELS "hemom;integration;continue" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Debug" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;114;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_Continue_Setup "C:/STU/devel/ReMoM/build-dbg/bin/Release/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_Continue_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_Continue" LABELS "hemom;integration;continue" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Release" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;114;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_Continue_Setup "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_Continue_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_Continue" LABELS "hemom;integration;continue" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;114;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_Continue_Setup "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_Continue_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_Continue" LABELS "hemom;integration;continue" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;114;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_Continue_Setup NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_Continue_Run "C:/STU/devel/ReMoM/build-dbg/bin/Debug/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_save.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_Continue_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue" FIXTURES_SETUP "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" TIMEOUT "20" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Debug" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;127;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_Continue_Run "C:/STU/devel/ReMoM/build-dbg/bin/Release/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_save.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_Continue_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue" FIXTURES_SETUP "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" TIMEOUT "20" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Release" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;127;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_Continue_Run "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_save.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_Continue_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue" FIXTURES_SETUP "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" TIMEOUT "20" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;127;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_Continue_Run "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_save.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_Continue_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue" FIXTURES_SETUP "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" TIMEOUT "20" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;127;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_Continue_Run NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_Continue_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/Debug/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Debug/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_save.txt")
  set_tests_properties(HeMoM_Continue_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;142;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_Continue_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/Release/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Release/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_save.txt")
  set_tests_properties(HeMoM_Continue_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;142;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_Continue_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_save.txt")
  set_tests_properties(HeMoM_Continue_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;142;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_Continue_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_save.txt")
  set_tests_properties(HeMoM_Continue_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_Continue_Saved" LABELS "hemom;integration;continue" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;142;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_Continue_Assertions NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_NextTurn_Setup "C:/STU/devel/ReMoM/build-dbg/bin/Debug/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_NextTurn_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_NextTurn" LABELS "hemom;integration;nextturn" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Debug" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;168;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_NextTurn_Setup "C:/STU/devel/ReMoM/build-dbg/bin/Release/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_NextTurn_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_NextTurn" LABELS "hemom;integration;nextturn" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Release" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;168;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_NextTurn_Setup "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_NextTurn_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_NextTurn" LABELS "hemom;integration;nextturn" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;168;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_NextTurn_Setup "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/HeMoM.exe" "--newgame" "C:/STU/devel/ReMoM/assets/test_worldgen.ini" "--scenario" "C:/STU/devel/ReMoM/assets/test_worldgen_smoke.hms")
  set_tests_properties(HeMoM_NextTurn_Setup PROPERTIES  FIXTURES_SETUP "HeMoM_NextTurn" LABELS "hemom;integration;nextturn" TIMEOUT "10" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;168;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_NextTurn_Setup NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_NextTurn_Run "C:/STU/devel/ReMoM/build-dbg/bin/Debug/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_next_turn.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_NextTurn_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn" FIXTURES_SETUP "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" TIMEOUT "30" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Debug" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;181;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_NextTurn_Run "C:/STU/devel/ReMoM/build-dbg/bin/Release/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_next_turn.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_NextTurn_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn" FIXTURES_SETUP "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" TIMEOUT "30" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/Release" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;181;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_NextTurn_Run "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_next_turn.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_NextTurn_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn" FIXTURES_SETUP "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" TIMEOUT "30" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;181;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_NextTurn_Run "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/HeMoM.exe" "--continue" "--scenario" "C:/STU/devel/ReMoM/assets/test_continue_next_turn.hms" "--dump-save" "SAVE1.GAM")
  set_tests_properties(HeMoM_NextTurn_Run PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn" FIXTURES_SETUP "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" TIMEOUT "30" WORKING_DIRECTORY "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;181;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_NextTurn_Run NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HeMoM_NextTurn_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/Debug/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Debug/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_next_turn.txt")
  set_tests_properties(HeMoM_NextTurn_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;196;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HeMoM_NextTurn_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/Release/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/Release/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_next_turn.txt")
  set_tests_properties(HeMoM_NextTurn_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;196;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HeMoM_NextTurn_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/MinSizeRel/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_next_turn.txt")
  set_tests_properties(HeMoM_NextTurn_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;196;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HeMoM_NextTurn_Assertions "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/check_save_fields.exe" "C:/STU/devel/ReMoM/build-dbg/bin/RelWithDebInfo/SAVE1.txt" "C:/STU/devel/ReMoM/tests/assert_continue_next_turn.txt")
  set_tests_properties(HeMoM_NextTurn_Assertions PROPERTIES  FIXTURES_REQUIRED "HeMoM_NextTurn_Saved" LABELS "hemom;integration;nextturn" _BACKTRACE_TRIPLES "C:/STU/devel/ReMoM/tests/CMakeLists.txt;196;add_test;C:/STU/devel/ReMoM/tests/CMakeLists.txt;0;")
else()
  add_test(HeMoM_NextTurn_Assertions NOT_AVAILABLE)
endif()
