if(EXISTS "C:/STU/devel/ReMoM/build-dbg/tests/hello_test[1]_tests.cmake")
  include("C:/STU/devel/ReMoM/build-dbg/tests/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
