#ifndef MOX_SND_H
#define MOX_SND_H

#include "MOX_TYPE.H"



// WZD  dseg:9414
extern SAMB_ptr snd_left_button_click;
/* HACK */  extern uint32_t snd_left_button_click_size;

// WZD  dseg:9416 00                                              db    0
// WZD  dseg:9417 00                                              db    0
// WZD  dseg:9418 00                                              db    0
// WZD  dseg:9419 00                                              db    0

// WZD  dseg:941A
extern SAMB_ptr snd_standard_button_click;
/* HACK */  extern uint32_t snd_standard_button_click_size;



#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif

#endif  /* MOX_SND_H */
