#ifndef ST_HEAD_H
#define ST_HEAD_H

#include <ALLOC.H>  /* coreleft(), farcoreleft(), malloc(), farmalloc(), free(), farfree() */
#include <CONIO.H>
// #include <CTYPE.H>
// #include <DIR.H>
#include <DOS.H>
// #include <ERRNO.H>
#include <FCNTL.H>
#include <IO.H>
// #include <MEM.H>
// #include <PROCESS.H>
#include <STDIO.H>
#include <STDLIB.H>     /* ltoa() */
#include <STRING.H>
#include <SYS\STAT.H>
// #include <VALUES.H>

#include "ST_DBG.H"
#include "ST_DEF.H"
#include "ST_EMM.H"
#include "ST_LBX.H"
#include "ST_SA.H"
#include "ST_VID.H"

#include "STU_TYPE.H"
#include "STU_UTIL.H"

#endif /* ST_HEAD_H */
