/*
    STU Extract
    This module contains functions for extracting data from the game files, such as LBX archives.
    This is useful for debugging, modding, and understanding the game data formats.
    It may also be used for generating new game data or converting data to more modern formats.
    The functions in this module are not intended to be used in the main game loop, but rather as
    standalone utilities or tools for working with the game data.
    For example, Dump_TERRTYPE_LBX() can be used to read the TERRTYPE.LBX file and output its contents
    in a human-readable format, which can help with understanding the terrain types and how they are used
    in the game.

*/

#include "STU_XTRC.h"
#include "STU_FIO.h"
#include "../../MoX/src/Allocate.h"
#include "../../MoX/src/Fonts.h"
#include "../../MoX/src/LBX_Load.h"
#include "../../MoX/src/MOX_BASE.h"
#include "../../MoX/src/Init_Data/FONTS_LBX.h"

#include "../../ext/stu_compat.h"
#include <string.h>

/*
TERRTYPE.LBX
5 * 512

*/
void Dump_TERRTYPE_LBX(void)
{
    int16_t * terrtype = 0;
    char terrtype_lbx_file[] = "TERRTYPE.LBX";

    terrtype = (int16_t *)Near_Allocate_First((5 * 512));

    LBX_Load_Data_Static(terrtype_lbx_file, 0, (SAMB_ptr)terrtype, 0, 5, 512);

    /*
        The first record is used for Ocean, Tundra, and Desert.
    */

    STU_File_Open(NULL, "TERRTYPE_DUMP.txt", "w");
    for(int i = 0; i < 5; i++)
    {
        fprintf(stdout, "Record %d:\n", i);
        for(int j = 0; j < 512; j++)
        {
            fprintf(stdout, "%d ", terrtype[i * 512 + j]);
        }
        fprintf(stdout, "\n");
    }

    /*
        The second record is used for Mountain and Hills,
        but, for Hills, it is offset 16 values into the record.
        My current theory is that Hills was mean to be the third record.
        That might also account for the oddity of there being 16 and only 16 values in the third record.
    */

}



/*
    Emit_Byte_Array
    Writes a uint8_t array as formatted hex to the output file.
    16 bytes per line, with trailing comma.
*/
void Emit_Byte_Array(FILE * out, const char * name, const uint8_t * data, uint32_t size)
{
    uint32_t i;

    if(name != NULL)
    {
        fprintf(out, "const uint8_t %s[] =\n{\n", name);
    }

    for(i = 0; i < size; i++)
    {
        if((i % 16) == 0)
        {
            fprintf(out, "    ");
        }
        fprintf(out, "0x%02X", data[i]);
        if(i < (size - 1))
        {
            fprintf(out, ",");
        }
        if(((i % 16) == 15) || (i == (size - 1)))
        {
            fprintf(out, "\n");
        }
        else
        {
            fprintf(out, " ");
        }
    }

    if(name != NULL)
    {
        fprintf(out, "};\n");
    }
}



/*
    Emit_U16_Array
    Writes a uint16_t array as formatted hex to the output file.
    8 values per line.
*/
static void Emit_U16_Array(FILE * out, const uint16_t * data, int count)
{
    int i;

    for(i = 0; i < count; i++)
    {
        if((i % 8) == 0)
        {
            fprintf(out, "        ");
        }
        fprintf(out, "0x%04X", data[i]);
        if(i < (count - 1))
        {
            fprintf(out, ",");
        }
        if(((i % 8) == 7) || (i == (count - 1)))
        {
            fprintf(out, "\n");
        }
        else
        {
            fprintf(out, " ");
        }
    }
}



/*
    Emit_U8_Array
    Writes a uint8_t array as formatted hex to the output file.
    16 values per line.
*/
static void Emit_U8_Array(FILE * out, const uint8_t * data, int count)
{
    int i;

    for(i = 0; i < count; i++)
    {
        if((i % 16) == 0)
        {
            fprintf(out, "        ");
        }
        fprintf(out, "0x%02X", data[i]);
        if(i < (count - 1))
        {
            fprintf(out, ",");
        }
        if(((i % 16) == 15) || (i == (count - 1)))
        {
            fprintf(out, "\n");
        }
        else
        {
            fprintf(out, " ");
        }
    }
}



/*
    Extract_FONTS_LBX_0
    Loads FONTS.LBX entry [0] (font style data) and emits a
    struct s_FONTS_LBX_ENTRY_0 initialiser to the output file.
*/
void Extract_FONTS_LBX_0(FILE * out)
{
    SAMB_ptr data;
    struct s_FONT_HEADER * hdr;
    uint32_t entry_size;
    uint32_t glyph_size;

    data = LBX_Load("FONTS", 0);
    entry_size = lbxload_entry_length;
    hdr = (struct s_FONT_HEADER *)data;

    if(entry_size <= SZ_FONT_HDR)
    {
        fprintf(stderr, "Extract_FONTS_LBX_0: entry [0] too small (%u bytes)\n", entry_size);
        return;
    }

    glyph_size = entry_size - SZ_FONT_HDR;

    fprintf(out, "/*\n");
    fprintf(out, "    FONTS.LBX Entry [0] — Font Style Data\n");
    fprintf(out, "    Total size: %u bytes (header: %d, glyph data: %u)\n", entry_size, SZ_FONT_HDR, glyph_size);
    fprintf(out, "    Generated by Extract_FONTS_LBX_0()\n");
    fprintf(out, "*/\n");
    fprintf(out, "const struct s_FONTS_LBX_ENTRY_0 FONTS_LBX_ENTRY_0 =\n");
    fprintf(out, "{\n");
    fprintf(out, "    .header =\n");
    fprintf(out, "    {\n");

    fprintf(out, "        .current_colors =\n        {\n");
    Emit_U8_Array(out, hdr->current_colors, COLOR_SET_COUNT);
    fprintf(out, "        },\n");

    fprintf(out, "        .height = 0x%04X,\n", hdr->height);
    fprintf(out, "        .shadow_flag = 0x%02X,\n", hdr->shadow_flag);
    fprintf(out, "        .current_color_set = 0x%02X,\n", hdr->current_color_set);

    fprintf(out, "        .normal_colors =\n        {\n");
    Emit_U8_Array(out, hdr->normal_colors, COLOR_SET_COUNT);
    fprintf(out, "        },\n");

    fprintf(out, "        .highlight_colors =\n        {\n");
    Emit_U8_Array(out, hdr->highlight_colors, COLOR_SET_COUNT);
    fprintf(out, "        },\n");

    fprintf(out, "        .special_colors =\n        {\n");
    Emit_U8_Array(out, hdr->special_colors, COLOR_SET_COUNT);
    fprintf(out, "        },\n");

    fprintf(out, "        .current_base_height = 0x%04X,\n", hdr->current_base_height);
    fprintf(out, "        .current_vertical_spacing = 0x%04X,\n", hdr->current_vertical_spacing);
    fprintf(out, "        .current_horizontal_spacing = 0x%04X,\n", hdr->current_horizontal_spacing);

    fprintf(out, "        .current_font_widths =\n        {\n");
    Emit_U8_Array(out, hdr->current_font_widths, 96);
    fprintf(out, "        },\n");

    fprintf(out, "        .current_data_offsets =\n        {\n");
    Emit_U16_Array(out, hdr->current_data_offsets, 96);
    fprintf(out, "        },\n");

    fprintf(out, "        .base_height =\n        {\n");
    Emit_U16_Array(out, hdr->base_height, 8);
    fprintf(out, "        },\n");

    fprintf(out, "        .horizontal_spacing =\n        {\n");
    Emit_U16_Array(out, hdr->horizontal_spacing, 8);
    fprintf(out, "        },\n");

    fprintf(out, "        .vertical_spacing =\n        {\n");
    Emit_U16_Array(out, hdr->vertical_spacing, 8);
    fprintf(out, "        },\n");

    fprintf(out, "        .font_widths =\n        {\n");
    Emit_U8_Array(out, hdr->font_widths, 768);
    fprintf(out, "        },\n");

    fprintf(out, "        .data_offsets =\n        {\n");
    Emit_U16_Array(out, hdr->data_offsets, 768);
    fprintf(out, "        }\n");

    fprintf(out, "    },\n");

    fprintf(out, "    .glyph_data =\n    {\n");
    Emit_Byte_Array(out, NULL, data + SZ_FONT_HDR, glyph_size);
    fprintf(out, "    }\n");

    fprintf(out, "};\n");
    fprintf(out, "const uint32_t FONTS_LBX_ENTRY_0_SIZE = %u;\n\n\n", entry_size);
}



/*
    Extract_FONTS_LBX_1
    Loads FONTS.LBX entry [1] (border/outline data) and emits
    a raw byte array to the output file.
*/
void Extract_FONTS_LBX_1(FILE * out)
{
    SAMB_ptr data;
    uint32_t entry_size;

    data = LBX_Load("FONTS", 1);
    entry_size = lbxload_entry_length;

    fprintf(out, "/*\n");
    fprintf(out, "    FONTS.LBX Entry [1] — Border / Outline Data\n");
    fprintf(out, "    Total size: %u bytes\n", entry_size);
    fprintf(out, "    Generated by Extract_FONTS_LBX_1()\n");
    fprintf(out, "*/\n");

    Emit_Byte_Array(out, "FONTS_LBX_ENTRY_1", data, entry_size);
    fprintf(out, "const uint32_t FONTS_LBX_ENTRY_1_SIZE = %u;\n\n\n", entry_size);
}



/*
    Extract_FONTS_LBX_2
    Loads FONTS.LBX entry [2] (palette block) and emits a
    struct s_FONTS_LBX_PALETTE initialiser to the output file.
*/
void Extract_FONTS_LBX_2(FILE * out)
{
    SAMB_ptr palette_buf;
    SAMB_ptr pal_data;
    uint32_t entry_size;

    palette_buf = Allocate_Space(348);
    pal_data = LBX_Reload("FONTS", 2, palette_buf);
    entry_size = lbxload_entry_length;

    fprintf(out, "/*\n");
    fprintf(out, "    FONTS.LBX Entry [2] — Palette Block\n");
    fprintf(out, "    Total size: %u bytes\n", entry_size);
    fprintf(out, "    Generated by Extract_FONTS_LBX_2()\n");
    fprintf(out, "*/\n");
    fprintf(out, "const struct s_FONTS_LBX_PALETTE FONTS_LBX_ENTRY_2 =\n");
    fprintf(out, "{\n");

    fprintf(out, "    .rgb_palette =\n    {\n");
    Emit_Byte_Array(out, NULL, pal_data + 0x000, 768);
    fprintf(out, "    },\n");

    fprintf(out, "    .font_colors =\n    {\n");
    Emit_Byte_Array(out, NULL, pal_data + 0x300, 256);
    fprintf(out, "    },\n");

    fprintf(out, "    .palette_data_0x400 =\n    {\n");
    Emit_Byte_Array(out, NULL, pal_data + 0x400, 256);
    fprintf(out, "    },\n");

    fprintf(out, "    .mouse_palette =\n    {\n");
    Emit_Byte_Array(out, NULL, pal_data + 0x500, 4096);
    fprintf(out, "    },\n");

    fprintf(out, "    .remap_colors =\n    {\n");
    Emit_Byte_Array(out, NULL, pal_data + 0x1500, 96);
    fprintf(out, "    }\n");

    fprintf(out, "};\n");
    fprintf(out, "const uint32_t FONTS_LBX_ENTRY_2_SIZE = %u;\n\n", entry_size);
}



/*
    Extract_FONTS_LBX
    Top-level function: creates the output file and calls all three entry extractors.
*/
void Extract_FONTS_LBX(const char * out_path)
{
    FILE * out;

    out = stu_fopen(out_path, "w");
    if(out == NULL)
    {
        fprintf(stderr, "Extract_FONTS_LBX: cannot open %s for writing\n", out_path);
        return;
    }

    fprintf(out, "/*\n");
    fprintf(out, "    FONTS_LBX.c — Embedded FONTS.LBX data\n");
    fprintf(out, "    Generated by Extract_FONTS_LBX() — do not edit by hand.\n");
    fprintf(out, "    Regenerate from original FONTS.LBX using the extraction tool.\n");
    fprintf(out, "*/\n\n");
    fprintf(out, "#include \"FONTS_LBX.h\"\n\n\n");

    Extract_FONTS_LBX_0(out);
    Extract_FONTS_LBX_1(out);
    Extract_FONTS_LBX_2(out);

    fclose(out);
    fprintf(stdout, "Extract_FONTS_LBX: wrote %s\n", out_path);
}
