/*
    Advisor Screen

    WIZARDS.EXE
        ovr076
    
*/

#ifndef ADVSRSCR_H
#define ADVSRSCR_H

#include "MoM.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr076
*/

// WZD o76p01
void Advisor_Screen(int16_t advisor_idx);

// WZD o76p02
// WZD o76p03
// WZD o76p04
// WZD o76p05
// WZD o76p06
// WZD o76p07
// WZD o76p08
// WZD o76p09
// WZD o76p10

// WZD o76p11
void GrandVizier_Window(void);




#ifdef __cplusplus
}
#endif


#endif  /* ADVSRSCR_H */
