/*
    AI - Data

    WIZARDS.EXE
        ¿ ovr145 ?
*/

#ifndef AIDUDES_H
#define AIDUDES_H

#include "MoM.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr145
*/

// WZD o145p01
int16_t AI_Accept_Mercenaries(int16_t player_idx, int16_t cost);

// WZD o145p02
// void AI_Overland_Turn__WIP(void);

// WZD o145p03
// AI_Continent_Eval()

// WZD o145p04
// AI_Power_Distrib()

// WZD o145p05
// WIZ_IsSpellKnown()

// WZD o145p06
// WIZ_KnownSpellCount()

// WZD o145p07
// AI_OVL_Eval_Assets()

// WZD o145p08
// AI_Count_Active_Wars()

// WZD o145p09
// sub_D405F()

// WZD o145p10
int16_t Map_Square_Unit_Count(int16_t wx, int16_t wy, int16_t wp);

// WZD o145p11
// AI_Alchemy()

// WZD o145p12
// AI_Tax_And_Farmers()

// WZD o145p13
// AI_SetNeutralFarmers()

// WZD o145p14
// AI_ExcessBuilders()

// WZD o145p15
// AI_StasisDisband()

// WZD o145p16
// EMM_Map_CONTXXX()

// WZD o145p17
// CONTX_CreateChains()

// WZD o145p18
// CONTX_CreateLChains()



#ifdef __cplusplus
}
#endif

#endif  /* AIDUDES_H */
