/*
    WIZARDS.EXE
        ovr149

    MoO2
        GENDRAW
*/

#ifndef GENDRAW_H
#define GENDRAW_H

#include "MoX.H"

#ifdef __cplusplus
extern "C" {
#endif



// WZD o149p01
// GUI_Confirm_Dialog  
// WZD o149p02
// GUI_DrawConfrmDialog
// WZD o149p03
// GUI_WarningType1    

// WZD o149p04
// drake178: GUI_WarningType0()
void GUI_WarningType0(char * msg);

// WZD o149p05
// GUI_ShowRedMessage  
// WZD o149p06
// GUI_DrawRedMessage  
// WZD o149p07
// GUI_ListSelect_Dlg  
// WZD o149p08
// GUI_DrawListSelector
// WZD o149p09
// GUI_SetListSelBounds
// WZD o149p10
// GUI_LoadNotifyGfx   
// WZD o149p11
// GUI_Notify_Dialog   
// WZD o149p12
// GUI_DrawNotifyDialog
// WZD o149p13
// GUI_Familiar_Notify 
// WZD o149p14
// GUI_DrawFamiliarNtfy
// WZD o149p15
// HLP_NoResizeExpand  
// WZD o149p16
// HLP_DrawExpanding   
// WZD o149p17
// G_USW_DrawEHLines   
// WZD o149p18
// HLP_DrawExpandLines 
// WZD o149p19
// ITEM_GetViewDrawPos 
// WZD o149p20
// ITEM_ResetViewGrow  
// WZD o149p21
// EMM_Sandbox2VGAFILEH
// WZD o149p22
// EMM_VGAFILEH2Sandbox



#ifdef __cplusplus
}
#endif

#endif  /* GENDRAW_H */
