/*
    MAGIC.EXE
        ovr058
*/

#ifndef INTRO_H
#define INTRO_H



#ifdef __cplusplus
extern "C" {
#endif



/*
    MAGIC.EXE ovr058
*/

// MGC o58p1
void Draw_Logos(void);

// MGC o58p2
void VGA_Fade_Out_2(void);

// MGC o58p3
void VGA_Fade_Out_10(void);

// MGC o58p4
void VGA_Fade_Out_20(void);

// MGC o58p5
void VGA_Fade_In_2(void);

// MGC o58p6
void VGA_Fade_In_50(void);



#ifdef __cplusplus
}
#endif

#endif  /* INTRO_H */
