/*
    Items

    WIZARDS.EXE
        ovr109
*/

#ifndef ITEMS_H
#define ITEMS_H

#include "MOX/MOX_TYPE.H"



#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr109
*/

// WZD o109p01
void Player_Process_Item_Pool(int16_t player_idx, int16_t item_count, int16_t item_list[]);

// WZD o109p02
void Remove_Item(int16_t item_idx);

// WZD o109p03
void AI_Process_Item_Pool__STUB(int16_t player_idx, int16_t item_count, int16_t item_list[]);

// WZD o109p04
// drake178: AI_EquipHeroFirst()
// AI_EquipHeroFirst()

// WZD o109p05
// drake178: AI_EquipRemainder()
// AI_EquipRemainder()



#ifdef __cplusplus
}
#endif

#endif  /* ITEMS_H */
