/*
    Items

    WIZARDS.EXE
        ovr109
*/

#ifndef ITEMS_H
#define ITEMS_H

#include "MoX.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr109
*/

// WZD o109p01
// drake178: WIZ_AwardItems()
// WIZ_AwardItems()

// WZD o109p02
// drake178: ITEM_DeleteValue()
void ITEM_DeleteValue(int16_t item_idx);

// WZD o109p03
// drake178: AI_ProcessItems()
// AI_ProcessItems()

// WZD o109p04
// drake178: AI_EquipHeroFirst()
// AI_EquipHeroFirst()

// WZD o109p05
// drake178: AI_EquipRemainder()
// AI_EquipRemainder()



#ifdef __cplusplus
}
#endif

#endif  /* ITEMS_H */
