/*
    WIZARDS.EXE
        ovr160
    MAGIC.EXE
        ovr050

WZD
    Load_Screen
    Load_Screen_Draw
    Set_Load_Screen_Help_List
    Loaded_Game_Update
MGC
    Load_Screen
    Load_Screen_Draw

MoO2  Module: LOADSAVE

*/

#ifndef LOADSCR_MGC_H
#define LOADSCR_MGC_H

#include "MoM.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    MAGIC.EXE  ovr050
*/

// WZD o50p01
// GAME_New_Create()

// WZD o50p02
// GAME_WizardsLaunch()

// WZD o50p03
void Load_Screen_MGC__WIP(void);

// WZD o50p04
void Load_Screen_Draw_MGC__WIP(void);

// NewGame_Screen_1()
// NewGame_Screen_Draw_1()
// GAME_RandBookBinders()
// GAME_New_Screen_1()
// Draw_NewGame_Screen1()
// GAME_New_Screen_2()
// GAME_New_Screen_3()
// GAME_Draw_NewScr3()
// GAME_New_Screen_7()
// GAME_Draw_NewScr7()
// GAME_New_Screen_6()
// GAME_Draw_NewScr6()
// GAME_DrawRetortsStr()
// NEWG_DrawDefShelf()
// GAME_New_Screen_4()
// GAME_Draw_NewScr4()
// GAME_New_Screen_5()
// GAME_SpellSel_GUI()
// SCRN_Draw_NewScr5()
// SCRN_Draw_NewScr5_2()
// WIZ_CopyDefault()

// WZD o50p26
// Fade_Out()

// WZD o50p27
// VGA_Fade_In()

// WZD o50p28
void Set_Load_Screen_Help_List_MGC(void);

// HLP_Load_NewGOptions()
// HLP_Load_BannerSel()
// HLP_Load_PortraitSel()
// HLP_Load_WizardSel()
// HLP_Load_WizCreate()
// HLP_Load_RaceSel()
// STR_ListSeparator()
// CRP_Empty_Dialog_Fn2()
// CRP_Empty_Dialog_Fn1()
// Do_Toggle_Pages()



#ifdef __cplusplus
}
#endif

#endif  /* LOADSCR_MGC_H */
