#ifndef LOADSCR_H
#define LOADSCR_H


/*
WZD
ovr160
Load_Screen
Load_Screen_Draw
Load_Screen_Help
Loaded_Game_Update
*/



#ifdef __cplusplus
extern "C" {
#endif
    /* C and Asm Function Prototypes */


/*
    WIZARDS.EXE ovr160
*/

// WZD o160p01
void Load_Screen(void);

// WZD o160p02
void Load_Screen_Draw(void);

// WZD o160p03
void Load_Screen_Help(void);

// WZD o160p04
void Loaded_Game_Update(void);


#ifdef __cplusplus
}
#endif


#endif  /* LOADSCR_H */
