/*
    MAGIC.EXE
    ovr051
*/

#ifndef MAPGEN_H
#define MAPGEN_H

#include "MOX/MOX_TYPE.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    MAGIC.EXE
    ovr051
*/

// o51p01
void NEWG_CreateWorld__WIP(void);

// o51p02
// NEWG_EZ_MarkHadnLeft()

// o51p03
// NEWG_TileIsleExtend()

// o51p04
// NEWG_CreateTowers()

// o51p05
// NEWG_CreateCapitals()

// o51p06
// NEWG_ClearLandmasses()

// o51p07
// NEWG_EqualizeNodes()

// o51p08
// NEWG_SetSpecLands()

// o51p09
// NEWG_SetBaseLands()

// o51p10
// NEWG_CreateLands()

// o51p11
// NEWG_CreateNodes()

// o51p12
// NEWG_CreateNodeAura()

// o51p13
// NODE_IsAuraUnique()

// o51p14
// NEWG_SetNodeType()

// o51p15
// TILE_SetLandMass()

// o51p16
// NEWG_CreateEZs()

// o51p17
// NEWG_CreateEncounter()

// o51p18
// UU_UNIT_RandomRacial()

// o51p19
// NEWG_SetDeserts()

// o51p20
// NEWG_CreateShores()

// o51p21
// NEWG_RandomizeTiles()

// o51p22
// NEWG_CreateRiver()

// o51p23
// NEWG_SetRiverTiles()

// o51p24
// NEWG_CreateNeutrals()

// o51p25
// CTY_SetDefaultName()

// o51p26
// NEWG_CreateRoads()

// o51p27
// CRP_NEWG_CreatePathGrids()

// o51p28
// NEWG_CreateSpecials()

// o51p29
// NEWG_DesertSpecials()

// o51p30
// NEWG_HillSpecials()

// o51p31
// NEWG_MntnSpecials()

// o51p32
// NEWG_SetScoutingMaps()

// o51p33
// TILE_SetScouting()

// o51p34
// NEWG_SetMoveMaps()

// o51p35
// TILE_InvalidOutflow()

// o51p36
void Draw_Building_The_Worlds(int16_t percent);

// o51p37
// UNIT_Create()

// o51p38
// NEWG_AnimateOceans()

// o51p39
// TILE_IsOcean()

// o51p40
// TILE_HasNode()

// o51p41
// TILE_HasTower()

// o51p42
// TILE_IsForest()

// o51p43
// TILE_IsRiver()

// o51p44
// UU_TILE_IsRiverOutlet()

// o51p45
// UU_TILE_IsShore()

// o51p46
// TILE_IsMountains()

// o51p47
// TILE_IsHills()

// o51p48
// TILE_IsSwamp()

// o51p49
// TILE_IsDesert()

// o51p50
// TILE_IsGrasslands()

// o51p51
// TILE_GetFood()

// o51p52
// TILE_GetMaxPop()

// o51p53
// TILE_GetCatchment()

// o51p54
// UU_Empty_Tile_Fn()



#ifdef __cplusplus
}
#endif

#endif  /* MAPGEN_H */
