
#include "MoX.H"
#include "MoM_DEF.H"

/*
    Eh?
        MoM.H
            MoM_DEF.H
            MoX.H
                MoX_DEF.H
*/


// // sizeof=0x20
// struct s_UNIT
// {
//     /* 00 */  int8_t  world_x;
//     /* 01 */  int8_t  world_y;
//     /* 02 */  int8_t  world_plane;
//     /* 03 */  int8_t  owner_idx;
//     /* 04 */  int8_t  HalfMoves_Max;
//     /* 05 */  uint8_t type;
//     /* 06 */  int8_t  Hero_Slot;
//     /* 07 */  int8_t  Finished;
//     /* 08 */  int8_t  HMoves;
//     /* 09 */  int8_t  Target_X;
//     /* 0A */  int8_t  Target_Y;
//     /* 0B */  int8_t  Status;
//     /* 0C */  int8_t  Level;
//     /* 0D */  int8_t  Unused_0Dh;
//     /* 0E */  int16_t XP;
//     /* 10 */  int8_t  Move_Failed;
//     /* 11 */  int8_t  Damage;
//     /* 12 */  int8_t  Draw_Priority;
//     /* 13 */  int8_t  Unknown_13h;
//     /* 14 */  int16_t In_Tower;
//     /* 16 */  int8_t  Sight_Range;
//     /* 17 */  int8_t  Mutations;    // ; enum MUT_FLAGS
//     union {
//         int32_t Enchants;
//         struct {
//     /* 18 */  int16_t Enchants_LO;  // ; enum UE_FLAGS_L
//     /* 1A */  int16_t Enchants_HI;  // ; enum UE_FLAGS_H
//         }
//     }
//     /* 1C */  int8_t  Rd_Constr_Left;
//     /* 1D */  int8_t  Rd_From_X;
//     /* 1E */  int8_t  Rd_From_Y;
//     /* 1F */  int8_t  Unknown_1Fh;
//     /* 20 */
// };
