/*
    MAGIC.EXE
    ovr050
    ovr051
*/

#include "MOX/MOX_TYPE.H"



/*
    MAGIC.EXE
    ovr050
*/

// o50p01
void Newgame_Control(void);

// o50p02
// GAME_WizardsLaunch()

// o50p03
// Load_Screen()

// o50p04
// Load_Screen_Draw()

// o50p05
void Newgame_Screen_0__WIP(void);

// o50p06
void Newgame_Screen_0_Draw__WIP(void);

// o50p07
void Randomize_Book_Heights(void);

// o50p08
void GAME_New_Screen_1__WIP(void);

// o50p09
// Draw_NewGame_Screen1()

// o50p10
void GAME_New_Screen_2__WIP(void);

// o50p11
int16_t GAME_New_Screen_3__WIP(void);

// o50p12
// GAME_Draw_NewScr3()

// o50p13
void GAME_New_Screen_7__WIP(void);

// o50p14
// GAME_Draw_NewScr7()

// o50p15
int16_t GAME_New_Screen_6__WIP(void);

// o50p16
// GAME_Draw_NewScr6()

// o50p17
// GAME_DrawRetortsStr()

// o50p18
// NEWG_DrawDefShelf()

// o50p19
void GAME_New_Screen_4__WIP(void);

// o50p20
// GAME_Draw_NewScr4()

// o50p21
void GAME_New_Screen_5__WIP(void);

// o50p22
// GAME_SpellSel_GUI()

// o50p23
// SCRN_Draw_NewScr5()

// o50p24
// SCRN_Draw_NewScr5_2()

// o50p25
// WIZ_CopyDefault()

// o50p26
// Fade_Out()

// o50p27
// VGA_Fade_In()

// o50p28
// Set_Load_Screen_Help_List_MGC()

// o50p29
// HLP_Load_NewGOptions()

// o50p30
// HLP_Load_BannerSel()

// o50p31
// HLP_Load_PortraitSel()

// o50p32
// HLP_Load_WizardSel()

// o50p33
// HLP_Load_WizCreate()

// o50p34
// HLP_Load_RaceSel()

// o50p35
// STR_ListSeparator()

// o50p36
// CRP_Empty_Dialog_Fn2()

// o50p37
// CRP_Empty_Dialog_Fn1()

// o50p38
// Do_Toggle_Pages()




/*
    MAGIC.EXE
    ovr051
*/

// o51p01
// NEWG_CreateWorld()

// o51p02
// NEWG_EZ_MarkHadnLeft()

// o51p03
// NEWG_TileIsleExtend()

// o51p04
// NEWG_CreateTowers()

// o51p05
// NEWG_CreateCapitals()

// o51p06
// NEWG_ClearLandmasses()

// o51p07
// NEWG_EqualizeNodes()

// o51p08
// NEWG_SetSpecLands()

// o51p09
// NEWG_SetBaseLands()

// o51p10
// NEWG_CreateLands()

// o51p11
// NEWG_CreateNodes()

// o51p12
// NEWG_CreateNodeAura()

// o51p13
// NODE_IsAuraUnique()

// o51p14
// NEWG_SetNodeType()

// o51p15
// TILE_SetLandMass()

// o51p16
// NEWG_CreateEZs()

// o51p17
// NEWG_CreateEncounter()

// o51p18
// UU_UNIT_RandomRacial()

// o51p19
// NEWG_SetDeserts()

// o51p20
// NEWG_CreateShores()

// o51p21
// NEWG_RandomizeTiles()

// o51p22
// NEWG_CreateRiver()

// o51p23
// NEWG_SetRiverTiles()

// o51p24
// NEWG_CreateNeutrals()

// o51p25
// CTY_SetDefaultName()

// o51p26
// NEWG_CreateRoads()

// o51p27
// CRP_NEWG_CreatePathGrids()

// o51p28
// NEWG_CreateSpecials()

// o51p29
// NEWG_DesertSpecials()

// o51p30
// NEWG_HillSpecials()

// o51p31
// NEWG_MntnSpecials()

// o51p32
// NEWG_SetScoutingMaps()

// o51p33
// TILE_SetScouting()

// o51p34
// NEWG_SetMoveMaps()

// o51p35
// TILE_InvalidOutflow()

// o51p36
// NEWG_UpdateProgress()

// o51p37
// UNIT_Create()

// o51p38
// NEWG_AnimateOceans()

// o51p39
// TILE_IsOcean()

// o51p40
// TILE_HasNode()

// o51p41
// TILE_HasTower()

// o51p42
// TILE_IsForest()

// o51p43
// TILE_IsRiver()

// o51p44
// UU_TILE_IsRiverOutlet()

// o51p45
// UU_TILE_IsShore()

// o51p46
// TILE_IsMountains()

// o51p47
// TILE_IsHills()

// o51p48
// TILE_IsSwamp()

// o51p49
// TILE_IsDesert()

// o51p50
// TILE_IsGrasslands()

// o51p51
// TILE_GetFood()

// o51p52
// TILE_GetMaxPop()

// o51p53
// TILE_GetCatchment()

// o51p54
// UU_Empty_Tile_Fn()
