#ifndef SCASTSCR_H
#define SCASTSCR_H

/*
    Spell Casting Screen

    WIZARDS.EXE
    ovr070
*/

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr070

*/

// WZD o70p01

// WZD o70p02

// WZD o70p03
int16_t World_To_Screen(int16_t map_xw, int16_t map_yw, int16_t * unit_xw, int16_t * unit_yw);


// WZD o70p04

// WZD o70p05

// WZD o70p06

// WZD o70p07

// WZD o70p08

// WZD o70p09

// WZD o70p10

// WZD o70p11

// WZD o70p12

// WZD o70p13

// WZD o70p14



#ifdef __cplusplus
}
#endif

#endif  /* SCASTSCR_H */
