#ifndef SCASTSCR_H
#define SCASTSCR_H

/*
    Spell Casting Screen

    WIZARDS.EXE
    ovr070
*/

#include "MoX/MoX_TYPE.H"



#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr070

*/

// IDK_Spell_Casting_Screen                       ovr070
// sub_5CDB2                                      ovr070
// IDK_Spell_Casting_Screen_Draw                  ovr070
// World_To_Screen                                ovr070
// sub_5CFC9                                      ovr070
// sub_5CFFA                                      ovr070
// sub_5D0B3                                      ovr070
// sub_5D0E8                                      ovr070
// sub_5D0FF                                      ovr070
// sub_5D116                                      ovr070
// sub_5D12D                                      ovr070
// sub_5D144                                      ovr070
// sub_5D15B                                      ovr070
// sub_5D20A                                      ovr070
// sub_5D5D5                                      ovr070

// WZD o70p01

// WZD o70p02

// WZD o70p03

// WZD o70p04
int16_t World_To_Screen(int16_t map_wx, int16_t map_wy, int16_t * unit_wx, int16_t * unit_wy);

// WZD o70p05

// WZD o70p06

// WZD o70p07

// WZD o70p08

// WZD o70p09

// WZD o70p10

// WZD o70p11

// WZD o70p12

// WZD o70p13

// WZD o70p14



#ifdef __cplusplus
}
#endif

#endif  /* SCASTSCR_H */
