/*
    WIZARDS.EXE
        ovr100

    Moo2
        Module: COLONIZE

*/

#ifndef SETTLE_H
#define SETTLE_H

#include "MOX/MOX_TYPE.H"



#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE ovr100
*/

// WZD o100p01
void AI_MoveUnits__WIP(int16_t player_idx);

// WZD o100p02
void AI_UNIT_Meld__WIP(int16_t unit_idx);

// WZD o100p03
void AI_UNIT_Settle__WIP(int16_t unit_idx);

// WZD o100p04
// drake178: Do_Build_Outpost()
int16_t Do_Build_Outpost(void);

// WZD o100p05
// drake178: STK_SettleTile()
int16_t STK_SettleTile(int16_t troop_count, int16_t troops[]);

// WZD o100p06
void AI_UNIT_Move__WIP(int16_t unit_idx);

// WZD o100p07
// drake178: sub_8227A()
// sub_8227A()

// WZD o100p08
// drake178: sub_82377()
// sub_82377()

// WZD o100p09
// drake178: UNIT_PushOffTile()
void UNIT_PushOffTile(int16_t unit_idx);

// WZD o100p10
// drake178: TILE_UNIT_CanMoveTo()
int16_t Unit_Space_At_Square(int16_t wx, int16_t wy, int16_t wp, int16_t player_idx, int16_t unit_idx);

// WZD o100p11
void AI_UNIT_SeekTransprt__WIP(uint16_t unit_idx);

// WZD o100p12
void AI_UNIT_BuildRoad__WIP(int16_t unit_idx);

// WZD o100p13
int16_t Map_Square_Troops_Can_Plane_Shift(int16_t wx, int16_t wy, int16_t wp);



#ifdef __cplusplus
}
#endif

#endif  /* SETTLE_H */
