/*
    WIZARDS.EXE
        ovr130
*/

#ifndef SPELLS130_H
#define SPELLS130_H

#include "MOX/MOX_TYPE.H"



#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr130
*/

// WZD o130p01
void Hero_Slot_Types(int16_t unit_type_idx, int16_t item_slots[]);

// WZD o130p02
int16_t Cast_DeathWish(int16_t player_idx);

// WZD o130p03
int16_t Cast_GreatUnsummoning(int16_t player_idx);

// WZD o130p04
int16_t Cast_Black_Wind(int16_t player_idx);

// WZD o130p05
int16_t Apply_Drain_Power(int16_t player_idx);

// WZD o130p06
int16_t Cast_Earth_Lore(int16_t player_idx);

// WZD o130p07
// int16_t Cast_Spell_Binding(int16_t player_idx);
void Cast_Spell_Binding(int16_t player_idx);

// WZD o130p08
int16_t Cast_Change_Terrain(int16_t player_idx);

// WZD o130p09
int16_t Cast_Raise_Volcano(int16_t player_idx);

// WZD o130p10
int16_t Cast_Transmute(int16_t player_idx);

// WZD o130p11
int16_t Cast_Corruption(int16_t player_idx);

// WZD o130p12
int16_t Cast_Word_Of_Recall(int16_t player_idx);

// WZD o130p13
int16_t Cast_Enchant_Road(int16_t player_idx);

// WZD o130p14
int16_t Cast_Spell_Ward(int16_t player_idx);

// WZD o130p15
void Cast_Holy_Arms(int16_t player_idx);

// WZD o130p16
void Apply_Consecration(int16_t city_idx);

// WZD o130p17
void Apply_Subversion(int16_t player_idx);

// WZD o130p18
void Cast_NaturesAwareness(int16_t player_idx);



#ifdef __cplusplus
}
#endif

#endif  /* SPELLS130_H */
