/*
    Cityscape  (City Screen)

    WIZARDS.EXE
        ovr144
*/
#ifndef TST_CITYSCAPE_H
#define TST_CITYSCAPE_H

#include "MOX/MOX_TYPE.H"



#define NUM_CITYSCAPE_ROWS         15
#define NUM_CITYSCAPE_COLS         23



#ifdef __cplusplus
extern "C" {
#endif



void TST_Cityscape(int16_t city_idx, int16_t xstart, int16_t ystart, int16_t bldg_idx_1, int16_t bldg_idx_2);



#ifdef __cplusplus
}
#endif



#endif /* TST_CITYSCAPE_H */
