/*
    WIZARDS.EXE
        ovr129
*/

#ifndef WZD_O129_H
#define WZD_O129_H

#include "MoX.H"

#ifdef __cplusplus
extern "C" {
#endif



/*
    WIZARDS.EXE  ovr129
*/

// WZD o129p01
// sub_ACD60()

// WZD o129p02
// OVL_ConvSpellAttack()

// WZD o129p03
// UNIT_ConvSpellATK()

// WZD o129p04
// sub_AD1F0()

// WZD o129p05
// sub_AD46B()

// WZD o129p06
int16_t CTY_CallTheVoid__STUB(int16_t city_idx);

// WZD o129p07
// CTY_CounterSpell()

// WZD o129p08
// UNIT_ChaosChannel()

// WZD o129p09
// sub_ADC3E()

// WZD o129p10
// sub_ADDA2()

// WZD o129p11
// sub_AE017()

// WZD o129p12
// sub_AE352()

// WZD o129p13
// sub_AE51E()

// WZD o129p14
// sub_AE8B0()

// WZD o129p15
int16_t CTY_Earthquake__STUB(int16_t city_idx, int16_t * list_count, int16_t list_array[]);

// WZD o129p16
// sub_AEDB1()



#ifdef __cplusplus
}
#endif



#endif /* WZD_O129_H */
